"use client";
import { useEffect, useState } from "react";
import { AppShell } from "../components/AppShell";
import { ProductReview } from "../components/ProductReview";
import { api } from "../lib/api";
import type { ProductDraft } from "../lib/types";

const cards=[["Total Products","12","info"],["Draft Products","4",""],["Review Required","1","warning"],["Approved","5","success"],["Ready for Amazon","2","success"],["Submitted","0",""]];
export default function Home(){const [draft,setDraft]=useState<ProductDraft>(api.sample),[connected,setConnected]=useState<"checking"|"connected"|"offline">("checking");useEffect(()=>{api.health().then(()=>setConnected("connected")).catch(()=>setConnected("offline"));api.products().then(data=>data.products[0]&&setDraft(data.products[0])).catch(()=>{})},[]);return <AppShell><div className="content"><div className="page-title"><div><h1>Dashboard</h1><p>Prepare product listings without routine Seller Central data entry.</p></div><span className={`status ${connected}`}>{connected==="connected"?"● Backend connected":connected==="checking"?"◌ Checking backend":"● Demo mode · Backend offline"}</span></div><div className="cards">{cards.map(([name,value,kind])=><article className={`card ${kind}`} key={name}><span>{name}</span><strong>{value}</strong></article>)}</div><div className="grid"><section className="panel workflow"><h2>Product workflow</h2><ol>{["Source","Category","Auto-Fill","Review","Attributes","Variants","Amazon Mapping","Validation","Preview","Submit"].map((step,i)=><li className={i<3?"done":i===3?"current":""} key={step}><b>{i+1}</b>{step}</li>)}</ol></section><section className="panel"><h2>Recent activity</h2><div className="activity"><b>{draft.name}</b><span>Auto-fill completed</span><em>Review required · Just now</em></div><div className="activity"><b>Cream Kerala Cotton Kasavu Saree</b><span>Approved</span><em>Ready for mapping · Today</em></div></section></div><ProductReview draft={draft}/></div></AppShell>}
