import type { Category, ProductDraft } from "./types";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://127.0.0.1:8000";
const sample: ProductDraft = { id:"kurti-001", name:"Blue Long Cotton Floral Kurti", category:"women_kurti", status:"Review required", updatedAt:"Just now", actionRequired:["fabric_type","colour","pattern","neck_style","sleeve_length","garment_length"], localIssues:[], fields:[
  {attribute:"title",value:"Blue Long Cotton Floral Kurti",source:"manual",confidence:1,review_state:"manual"}, {attribute:"brand",value:"KHAGATARA",source:"manual",confidence:1,review_state:"manual"}, {attribute:"fabric_type",value:"Cotton",source:"description",confidence:.86,review_state:"medium"}, {attribute:"colour",value:"Blue",source:"filename",confidence:.84,review_state:"medium"}, {attribute:"pattern",value:"Floral",source:"description",confidence:.86,review_state:"medium"}, {attribute:"neck_style",value:"Round Neck",source:"description",confidence:.86,review_state:"medium"}, {attribute:"sleeve_length",value:"Three Quarter Sleeve",source:"description",confidence:.86,review_state:"medium"}, {attribute:"garment_length",value:"Long",source:"description",confidence:.86,review_state:"medium"}, {attribute:"size",value:"M",source:"manual",confidence:1,review_state:"manual"}
] };

async function request<T>(path:string, options?:RequestInit):Promise<T>{ const res=await fetch(`${API_URL}${path}`,{...options,headers:{"Content-Type":"application/json",...(options?.headers??{})}}); if(!res.ok) throw new Error(`Request failed (${res.status})`); return res.json() as Promise<T>; }
export const api={ health:()=>request<{status:string}>("/api/health"), categories:()=>request<{categories:Category[]}>("/api/categories"), products:()=>request<{products:ProductDraft[]}>("/api/products"), product:(id:string)=>request<ProductDraft>(`/api/products/${id}`), approve:(id:string,accept:string[],edits:Record<string,unknown>)=>request<ProductDraft>(`/api/products/${id}/review/approve`,{method:"POST",body:JSON.stringify({accept,edits)}), headers:{}), sample, API_URL };
